//! Enum tables automatically generated from the CANboat database.
//! Included at compile time through `build.rs`.

// Generated by build.rs
#![allow(clippy::all)]
include!(concat!(env!("OUT_DIR"), "/generated_lookups.rs"));
